name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install && cd web && npm install

      - name: Install and Build
        run: |
          npm run build

      - name: Upload WebApp as Artifact
        uses: actions/upload-pages-artifact@v3 
        with:
          path: ./web/dist/
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
